### ISSUE TITLE
MagicalPsi crashes the game

### ISSUE THREAD

**Issue by CommanderTvis** [wiiv/MagicalPsi#14] opened 2019-02-16 15:43 UTC
Game crashes, when I try to wear Psi armor.

**Comment by CommanderTvis** [comment] 2019-02-16 15:44
https://gist.github.com/CommanderTvis/1a1b298c43e6d286327acc6d66911ae2
This is the crash-report.

**Comment by Hubry** [comment] 2019-02-18 11:11
Duplicate of #10 and #11, fixed in #12 but Wiiv still hasn't released a build despite he'll do it two weeks ago.

**Closed** 2019-02-18 16:33 UTC
